### ISSUE TITLE
Additional Channel of Resolution Info

### ISSUE THREAD

**Issue by Pamphlett** [minwoo0611/Awesome-3D-LiDAR-Datasets#2]
Hi Kevin,

Thanks for your great project! I'm wondering if it's possible to indicate also the channel of resolution (number of lines) for the rotating LiDARs. As it is also critical information for many applications.
Cheers!

Pengyu

**Comment by minwoo0611** [comment]
Hello, Pengyu.

It seems be a great suggestion! As this repository is recently opened, it does not include the lots of information. However, I'll add some of informations more in recent future. Since your suggestion with the channel of resolution is important, I'll also include this information.

Thank you for your suggestion!

Minwoo

**Comment by minwoo0611** [comment]
I added this information in table. Again, thank you for your suggestion and as this issue seems be clear, I will close the issue. If you have a further suggestion, feel free to open the issue!
