### ISSUE TITLE
Whether there are data sets with very similar scene ？

### ISSUE THREAD

**Issue by kahowang** [minwoo0611/Awesome-3D-LiDAR-Datasets#4]
Dear Minwoo,

Thank you very much for your great work! 

I noticed that in the `bridge` dataset, you mentioned a large number of similar scenes. Recently, I want to conduct some tests on the degradation of laser in such scenes. Would you like to ask me, in addition to the similar scenes on the `bridge` mentioned above, are there similar scenes like `highways` and `tunnels` in the` HeLiPR` Sequences?

Warm regards,
Kaho

**Comment by minwoo0611** [comment]
Dear Kaho,

Thank you for reaching out again!

I'm glad to inform you that our `bridge` place does include a significant number of similar scenes featuring bridges and freeways. However, in regards to your inquiry about highways and tunnels, these specific types of scenes are not present in the `HeLiPR dataset`.

On another note, when considering urban environments like `Town` places, our dataset does encompass data from narrow alleys. It's important to note that in these alleys, the scanning area of LiDAR is not fully utilized due to the confined space, which results in a reduction of data quality. Moreover, the unique characteristics of these narrow alleys might present scenes that appear somewhat similar to each other. I hope this information is useful for your research.

Best regards,
Minwoo

**Comment by kahowang** [comment]
Dear Minwoo,

Thank you very much for your reply !!!
I will test these great dataset recently, what a wonderful work ~

Warm regards,
Kaho
